-- SWITCH TO THE CONTAINER TO CREATE THE USER
ALTER SESSION SET CONTAINER = XEPDB1;
-- ========================================
-- TABLESPACE CREATION
CREATE TABLESPACE DATA_TABLES_MATBRITANICO
DATAFILE 'C:\APP\SEBAS\PRODUCT\21C\ORADATA\XE\data_tables_MatBritanico_01.dbf'
SIZE 50M
AUTOEXTEND ON NEXT 50M
MAXSIZE 200M;

CREATE TABLESPACE INDEXES_MATBRITANICO
DATAFILE 'C:\APP\SEBAS\PRODUCT\21C\ORADATA\XE\indexes_MatBritanico_01.dbf'
SIZE 20M
AUTOEXTEND ON NEXT 20M
MAXSIZE 180M;

 
CREATE TEMPORARY TABLESPACE TEMP_MATBRITANICO
TEMPFILE 'C:\APP\SEBAS\PRODUCT\21C\ORADATA\XE\temp_MatBritanico_02.dbf'
SIZE 20M
AUTOEXTEND ON NEXT 10M
MAXSIZE 50M
EXTENT MANAGEMENT LOCAL
UNIFORM SIZE 2M;


CREATE USER matBrita IDENTIFIED BY brita123
DEFAULT TABLESPACE DATA_TABLES_MATBRITANICO
TEMPORARY TABLESPACE TEMP_MATBRITANICO
QUOTA UNLIMITED ON DATA_TABLES_MATBRITANICO
QUOTA UNLIMITED ON INDEXES_MATBRITANICO;

GRANT CONNECT, RESOURCE TO matBrita ;
GRANT CREATE VIEW, CREATE SYNONYM, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE, CREATE TYPE TO matBrita ;
GRANT CREATE SESSION TO matBrita ;

-- NEW CONNECTION Name Conexion_MatBritanico
-- user matBrita
-- password brita123
-- serviceName -> XEPDB1